FROM python:3.12-slim

WORKDIR /app

# system deps (kalau pakai requests, bs4, dll biasanya cukup)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy source
COPY app ./app

# default command
CMD ["python", "-m", "app.main"]
